#!/bin/bash

THIS_DIR=$PWD
cd ~
mv .vimrc .vimrc_bak > /dev/null 2>&1
mv .vim .vim_bak > /dev/null 2>&1
ln -s ${THIS_DIR}/.vimrc
ln -s ${THIS_DIR}/.vim

cd ${THIS_DIR}/.vim/
mkdir bundle
cd bundle
git clone git@github.com:gmarik/vundle.git
vim -c BundleInstall!
